In [1]:
import cv2
import os
import sys
import numpy as np
import imutils
import math

In [2]:
# dataset has greyscale images.240X320X8 i.e 8 is the depth of each pixel. each pixel can store 8bit info.
#i.e each bit can for any number by combination of 8 bits of 0 and 1. 
#i.e any number between 0-255 can be taken by each pixel 

sample_image = cv2.imread("C:\\Users\\MUJ\\Desktop\\minor\\casia b\\silhouettes\\silhouette\\001\\nm-01\\090\\001-nm-01-090-047.png",0)
sample_image_rgb = cv2.imread("C:\\Users\\MUJ\\Desktop\\minor\\casia b\\silhouettes\\silhouette\\001\\nm-01\\090\\001-nm-01-090-047.png")

In [3]:
#cany first reduces noise in image by 5*5 filter then applies sobel kernel to find edge gradient and direction for each pixelAfter getting gradient magnitude and direction, a full scan of image is done to remove any unwanted pixels which may notconstitutethe edge.For this, at every pixel, pixel is checked if it is a local maximum in its neighborhood in the direction of gradientFor this, we need two threshold values, minVal and maxVal. Any edges with intensity gradient more than maxVal are sure to be edges and those below minVal are sure to be non-edges, so discarded. Those who lie between these two thresholds are classified edges or non-edges based on their connectivityIf they are connected to "sure-edge" pixels, they are considered to be part of edges. Otherwise, they are also discarded.
#First argument is our input image. Second and third arguments are our minVal and maxVal respectively. Third argument is aperture_size. It is the size of Sobel kernel used for find image gradients. By default it is 3. Last argument is L2gradient which specifies the equation for finding gradient magnitude. If it is True, it uses the equation mentioned above which is more accurate, otherwise it uses this function: Edge_Gradient(G)=|Gx|+|Gy|. By default, it is False.
egded_image = cv2.Canny(sample_image,200,255)#any pixel value lying greater than or equal to 200 is considered as edge value 
dilated = cv2.dilate(egded_image,None,iterations=1)
cv2.imshow("edged",egded_image)
cv2.imshow("test",sample_image)
cv2.imshow("dialated",dilated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#Contour finding on original image

#using otsu binarisation
#For this, our cv.threshold() function is used, but pass an extra flag, cv.THRESH_OTSU. For threshold value, simply pass zero. 
#Then the algorithm finds the optimal threshold value and returns you as the second output, retVal. 
#If Otsu thresholding is not used, retVal is same as the threshold value you used.
# cv2.threshold(greyscale image,0 as threshold value,cz the otsu will find its own threshold, will not use our given value,maxval,flag to use otsu)
#thresh gets the modified image
ret,thresh = cv2.threshold(sample_image,0,255,0)
cv2.imshow("threshold_orig",thresh)
# three arguments in cv.findContours() function, first one is source image, second is contour retrieval mode, 
#third is contour approximation method. And it outputs a modified image, the contours and hierarchy. 
#contours is a Python list of all the contours in the image. 
#Each individual contour is a Numpy array of (x,y) coordinates of boundary points of the object.
im2, contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

cnt = contours[0]
leftmost = tuple(cnt[cnt[:,:,0].argmin()][0])
rightmost = tuple(cnt[cnt[:,:,0].argmax()][0])
topmost = tuple(cnt[cnt[:,:,1].argmin()][0])
bottommost = tuple(cnt[cnt[:,:,1].argmax()][0])

print(leftmost)
print(rightmost)
print(bottommost)
print(topmost)


# cv2.drawContours function is used. It can also be used to draw any shape provided you have its boundary points. 
#Its first argument is source image, second argument is the contours which should be passed as a Python list, 
#third argument is index of contours (useful when drawing individual contour. 
#To draw all contours, pass -1) and remaining arguments are color, thickness etc.
cv2.drawContours(thresh, contours, -1, (0,255,0), 3)
pixel = sample_image_rgb[leftmost[1],leftmost[0]]
print(pixel)
cv2.circle(thresh,(rightmost[1],bottommost[0]),50,(255,255,255),-1)

cv2.imshow("test",sample_image_rgb)
cv2.imshow("threshold",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

(276, 184)
(313, 118)
(277, 190)
(293, 51)
[255 255 255]


In [5]:
# Main Code to find the left most and the rightmost points

thresh = cv2.threshold(sample_image, 45, 255, cv2.THRESH_BINARY)[1]#further thresholding 
#erode function:-
#So what happends is that, all the pixels near boundary will be discarded depending upon the size of kernel. 
#So the thickness or size of the foreground object decreases or simply white region decreases in the image. 
#It is useful for removing small white noises, detach two connected objects etc.
thresh = cv2.erode(thresh, None, iterations=2)
thresh = cv2.dilate(thresh, None, iterations=2)
cv2.imshow("dilate",thresh)
cv2.imwrite("C:\\Users\\MUJ\\Desktop\\Gray_Image.jpg", thresh.copy());

cv2.waitKey(0)
cv2.destroyAllWindows()

#Find the contour of the binary image
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts) #graps only the contours points from cnts 
c = max(cnts, key=cv2.contourArea)
#area = cv2.contourArea(cnt[50])
#print("area is "+ str(area))

#The extreme most points
extLeft = tuple(c[c[:, :, 0].argmin()][0])
extRight = tuple(c[c[:, :, 0].argmax()][0])
extTop = tuple(c[c[:, :, 1].argmin()][0])
extBot = tuple(c[c[:, :, 1].argmax()][0])

print(extBot)
print(extRight)
cv2.drawContours(sample_image_rgb, [c], -1, (0, 255, 255), 2)
cv2.circle(sample_image_rgb, (extRight[0],extBot[1]), 3, (0, 0, 255), -1)
cv2.circle(sample_image_rgb, extBot, 3, (255, 255, 0), -1)


cv2.imshow("test",sample_image_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()


print(extRight)


(277, 190)
(313, 118)
(313, 118)


In [6]:
print(cnts[0])

[[[291  52]]

 [[288  55]]

 [[288  69]]

 [[289  70]]

 [[289  72]]

 [[290  73]]

 [[291  73]]

 [[292  74]]

 [[292  82]]

 [[291  83]]

 [[291  86]]

 [[290  87]]

 [[290  98]]

 [[289  99]]

 [[289 100]]

 [[286 103]]

 [[286 106]]

 [[285 107]]

 [[285 108]]

 [[283 110]]

 [[283 111]]

 [[281 113]]

 [[281 117]]

 [[280 118]]

 [[278 118]]

 [[278 122]]

 [[282 122]]

 [[282 118]]

 [[283 117]]

 [[287 117]]

 [[288 118]]

 [[288 126]]

 [[289 127]]

 [[289 130]]

 [[288 131]]

 [[288 132]]

 [[287 133]]

 [[287 134]]

 [[286 135]]

 [[286 136]]

 [[284 138]]

 [[284 139]]

 [[283 140]]

 [[283 141]]

 [[281 143]]

 [[281 144]]

 [[280 145]]

 [[280 147]]

 [[279 148]]

 [[279 156]]

 [[280 157]]

 [[280 163]]

 [[281 164]]

 [[281 171]]

 [[282 172]]

 [[282 174]]

 [[283 175]]

 [[283 178]]

 [[282 179]]

 [[282 180]]

 [[280 182]]

 [[279 182]]

 [[277 184]]

 [[277 190]]

 [[282 190]]

 [[283 189]]

 [[285 189]]

 [[286 188]]

 [[296 188]]

 [[297 187]]

 [[303 187]]

 [[304

In [18]:
"""
    Main Code Over here

"""
def findDistance(sample_image,sample_image_rgb,para):
    thresh = cv2.threshold(sample_image, 45, 255, cv2.THRESH_BINARY)[1]
    
    #threshold gives a binary image as output,
    #that contains foreground with white and background with black 
    #1. earlier it was grey scale image,now a binary image that contains either 0 or 1
    thresh = cv2.erode(thresh, None, iterations=2)#removes unnecessary noises near the boundry,detach almost connected parts aswell 
    thresh = cv2.dilate(thresh, None, iterations=2)#thickens the boundry
    #cv2.imshow("thresh",thresh)
    #cv2.imshow("sample",sample_image)

    #Find the ccontour of the binary image
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)#just graps the countours from above received cnts that also contains other info 
    c = max(cnts, key=cv2.contourArea)

    #The extreme most points
    extLeft = tuple(c[c[:, :, 0].argmin()][0])
    extRight = tuple(c[c[:, :, 0].argmax()][0])
    extTop = tuple(c[c[:, :, 1].argmin()][0])
    extBot = tuple(c[c[:, :, 1].argmax()][0])
    
    """
        In the below code :
            1) We are considering the points only below fist level that is coordinates with y value greater than that
                of fist
            2) In those values we are picking the rightmost and leftmost point that eventually comes out to
                be the foot points
        
    """
    maximum_y_r = -999
    maximum_x_r = -999
    maximum_x_l = extLeft[0]
    maximum_y_l = -999 
    
    for i in cnts[0]:
        for k in i:
            if k[1] > 150:
                if maximum_x_r < k[0]:
                    maximum_x_r = k[0]
                    maximum_y_r = k[1]
                        
    maximum_x_l = maximum_x_r
    maximum_y_l = -999 
    for i in cnts[0]:
        for k in i:
            if k[1] > maximum_y_r - 10:
                if maximum_x_l > k[0]:
                    maximum_x_l = k[0]
                    maximum_y_l = k[1]

    cv2.circle(sample_image_rgb, (maximum_x_r,maximum_y_r), 3, (0, 0, 255), -1)#for creating points on image
    cv2.circle(sample_image_rgb, (maximum_x_l,maximum_y_l), 3, (255, 255, 0), -1)
    
    #if y pixel of left foot is greater choose that y value 
    if maximum_y_l > maximum_y_r:
        b=maximum_y_l
    else:
        b=maximum_y_r
        
    cv2.circle(sample_image_rgb,(extTop[0],b), 3, (255, 0, 255), -1)
    cv2.circle(sample_image_rgb,extTop, 3, (255, 0, 0), -1)
    #to make line of height 
    cv2.line(sample_image_rgb,(extTop[0],extTop[1]),(extTop[0],b),(255,0,0),1)
    
    x=extLeft[0]
    y=extTop[1]
    w=extRight[0]-extLeft[0]
    h=extBot[1]-extTop[1]
    
    if para==1:
        cv2.rectangle(sample_image_rgb,(x,y),(x+max(width_list),y+max(height_list)),(255,255,0),1)
        cv2.imshow("box",sample_image_rgb)
    
    cv2.imshow("sample",sample_image_rgb)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    dx2 = (maximum_x_r-extBot[0])**2          # (200-10)^2
    dy2 = (maximum_y_r-extBot[1])**2          # (300-20)^2
    distance = math.sqrt(dx2 + dy2)
    
    

    hgt = b-extTop[1]
    
    return distance,hgt,w,x,y

In [19]:
#def BoundingBox(sample_image_rgb,mean_height,w,x,y):
#    cv2.rectangle(sample_image_rgb,(x,y),(x+w,(y+mean_height)),(255,255,0),1)
    #cv2.imshow("box",sample_image_rgb)
    

In [20]:
#images broken from between are not considered in calculating the height of the person and does not give apprpriate boundry box as well .
sample_image_path = "C:\\Users\\MUJ\\Desktop\\minor\\casia b\\silhouettes\\silhouette\\006\\nm-04\\090\\006-nm-04-090-"
sample_image_rgb_path = "C:\\Users\\MUJ\\Desktop\\minor\\casia b\\silhouettes\\silhouette\\006\\nm-04\\090\\006-nm-04-090-"

distance_list = []
height_list = []
width_list=[]

for i in range(69,111):
    sample_image = cv2.imread(sample_image_path + "{0:03}".format(i) +".png",0)
    sample_image_rgb = cv2.imread(sample_image_rgb_path + "{0:03}".format(i) +".png") 
    length,height,width,x,y = findDistance(sample_image,sample_image_rgb,0)
    distance_list.append(round(length))
    #discarding points that lie around the neck in height_list 
    if height>=120:
        height_list.append(height)
    width_list.append(width)   
    
mean_height=sum(height_list)//len(height_list)     

#to make a boundry box pass 1 as a parameter in findDistance
for i in range(69,111):
    sample_image = cv2.imread(sample_image_path + "{0:03}".format(i) +".png",0)
    sample_image_rgb = cv2.imread(sample_image_rgb_path + "{0:03}".format(i) +".png") 
    cv2.imshow("box",sample_image_rgb)
    length,height,width,x,y = findDistance(sample_image,sample_image_rgb,1)    
    
w=max(width_list)
print("max width is"+str(w))
j=0


#for i in range(69,111):
#    sample_image_new = cv2.imread(sample_image_rgb_path + "{0:03}".format(i) +".png",0)    
#    print(x_list[j],y_list[j])
 #   cv2.imshow("sample",sample_image_new)
  #  BoundingBox(sample_image_rgb,mean_height,w,x_list[j],y_list[j]) 
   # j=j+1

print(distance_list)
min_ = distance_list[0]
count = 1
cycle_length = []

      
#BoundingBox(sample_image_rgb,mean_height,width)

for i in range(1,len(distance_list)):
    temp = min_ - distance_list[i]
    if temp > 0 and temp < 5:
        count = i
        break
print("height_list is:")        
print(height_list) 

print("mean height is:"+ str(mean_height))

print("Cycle Length = {} ".format(count))

max width is78
[56, 52, 41, 31, 19, 18, 18, 19, 18, 18, 75, 58, 50, 45, 39, 21, 34, 48, 60, 67, 73, 76, 73, 67, 59, 48, 37, 20, 21, 20, 20, 20, 18, 16, 63, 1589, 37, 34, 22, 17, 36, 50]
height_list is:
[123, 125, 126, 128, 130, 122, 121, 123, 124, 126, 127, 130, 127, 124, 121, 122, 124, 126, 127, 129, 131, 132, 131, 130, 128, 124, 122, 124, 125, 127, 128]
mean height is:126
Cycle Length = 1 
