In [3]:
import cv2
import os
import sys
import numpy as np
import imutils
import math

In [2]:
sample_image = cv2.imread("D:\\MINOR_PROJECT\\casia b\\silhouettes\\001\\nm-01\\090\\001-nm-01-090-047.png",0)
sample_image_rgb = cv2.imread("D:\\MINOR_PROJECT\\casia b\\silhouettes\\001\\nm-01\\090\\001-nm-01-090-047.png")

In [84]:


egded_image = cv2.Canny(sample_image,200,255)

dilated = cv2.dilate(egded_image,None,iterations=1)
cv2.imshow("edged",egded_image)
cv2.imshow("test",sample_image)
cv2.imshow("dialated",dilated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#Contour finding on original image
ret,thresh = cv2.threshold(sample_image,0,255,0)
im2, contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
leftmost = tuple(cnt[cnt[:,:,0].argmin()][0])
rightmost = tuple(cnt[cnt[:,:,0].argmax()][0])
topmost = tuple(cnt[cnt[:,:,1].argmin()][0])
bottommost = tuple(cnt[cnt[:,:,1].argmax()][0])

print(leftmost)
print(rightmost)
print(bottommost)
print(topmost)



cv2.drawContours(thresh, contours, -1, (0,255,0), 3)
pixel = sample_image_rgb[leftmost[1],leftmost[0]]
cv2.circle(thresh,(rightmost[1],bottommost[0]),50,(255,255,255),-1)
print(pixel)
cv2.imshow("test",sample_image_rgb)
cv2.imshow("threshold",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

(276, 184)
(313, 118)
(277, 190)
(293, 51)
[255 255 255]


In [6]:
# Main Code to find the left most and the rightmost points

thresh = cv2.threshold(sample_image, 45, 255, cv2.THRESH_BINARY)[1]
thresh = cv2.erode(thresh, None, iterations=2)
thresh = cv2.dilate(thresh, None, iterations=2)

cv2.imshow("thres",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

#Find the ccontour of the binary image
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
c = max(cnts, key=cv2.contourArea)

#The extreme most points
extLeft = tuple(c[c[:, :, 0].argmin()][0])
extRight = tuple(c[c[:, :, 0].argmax()][0])
extTop = tuple(c[c[:, :, 1].argmin()][0])
extBot = tuple(c[c[:, :, 1].argmax()][0])

print(extBot)
print(extRight)
cv2.drawContours(sample_image_rgb, [c], -1, (0, 255, 255), 2)
cv2.circle(sample_image_rgb, (extRight[0],extBot[1]), 3, (0, 0, 255), -1)
cv2.circle(sample_image_rgb, extBot, 3, (255, 255, 0), -1)


cv2.imshow("test",sample_image_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()


print(extRight)


(277, 190)
(313, 118)
(313, 118)


In [77]:
print(cnts[0])

[[[291  52]]

 [[288  55]]

 [[288  69]]

 [[289  70]]

 [[289  72]]

 [[290  73]]

 [[291  73]]

 [[292  74]]

 [[292  82]]

 [[291  83]]

 [[291  86]]

 [[290  87]]

 [[290  98]]

 [[289  99]]

 [[289 100]]

 [[286 103]]

 [[286 106]]

 [[285 107]]

 [[285 108]]

 [[283 110]]

 [[283 111]]

 [[281 113]]

 [[281 117]]

 [[280 118]]

 [[278 118]]

 [[278 122]]

 [[282 122]]

 [[282 118]]

 [[283 117]]

 [[287 117]]

 [[288 118]]

 [[288 126]]

 [[289 127]]

 [[289 130]]

 [[288 131]]

 [[288 132]]

 [[287 133]]

 [[287 134]]

 [[286 135]]

 [[286 136]]

 [[284 138]]

 [[284 139]]

 [[283 140]]

 [[283 141]]

 [[281 143]]

 [[281 144]]

 [[280 145]]

 [[280 147]]

 [[279 148]]

 [[279 156]]

 [[280 157]]

 [[280 163]]

 [[281 164]]

 [[281 171]]

 [[282 172]]

 [[282 174]]

 [[283 175]]

 [[283 178]]

 [[282 179]]

 [[282 180]]

 [[280 182]]

 [[279 182]]

 [[277 184]]

 [[277 190]]

 [[282 190]]

 [[283 189]]

 [[285 189]]

 [[286 188]]

 [[296 188]]

 [[297 187]]

 [[303 187]]

 [[304

In [4]:
"""
    Main Code Over here

"""



def findDistance(sample_image,sample_image_rgb):
    thresh = cv2.threshold(sample_image, 45, 255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=2)

    #Find the ccontour of the binary image
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    c = max(cnts, key=cv2.contourArea)

    #The extreme most points
    extLeft = tuple(c[c[:, :, 0].argmin()][0])
    extRight = tuple(c[c[:, :, 0].argmax()][0])
    extTop = tuple(c[c[:, :, 1].argmin()][0])
    extBot = tuple(c[c[:, :, 1].argmax()][0])
    
    """
        In the below code :
            1) We are considering the points only below fist level is coordinates with y value greater than that
                of fist
            2) In those values we are picking the rightmost and leftmost point that eventually comes out to
                be the foot points
        
    """
    maximum_y_r = -999
    maximum_x_r = -999
    maximum_x_l = extLeft[0]
    maximum_y_l = -999 
    
    for i in cnts[0]:
        for k in i:
            if k[1] > 150:
                if maximum_x_r < k[0]:
                    maximum_x_r = k[0]
                    maximum_y_r = k[1]
                        
    maximum_x_l = maximum_x_r
    maximum_y_l = -999 
    for i in cnts[0]:
        for k in i:
            if k[1] > maximum_y_r - 10:
                if maximum_x_l > k[0]:
                    maximum_x_l = k[0]
                    maximum_y_l = k[1]

    cv2.circle(sample_image_rgb, (maximum_x_r,maximum_y_r), 3, (0, 0, 255), -1)
    cv2.circle(sample_image_rgb, (maximum_x_l,maximum_y_l), 3, (255, 255, 0), -1)
    cv2.imshow("test",sample_image_rgb)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    dx2 = (maximum_x_r-extBot[0])**2          # (200-10)^2
    dy2 = (maximum_y_r-extBot[1])**2          # (300-20)^2
    distance = math.sqrt(dx2 + dy2)
    
    return distance

In [11]:
sample_image_path = "D:\\MINOR_PROJECT\\casia b\\silhouettes\\006\\nm-01\\090\\006-nm-01-090-"
sample_image_rgb_path = "D:\\MINOR_PROJECT\\casia b\\silhouettes\\006\\nm-01\\090\\006-nm-01-090-"

distance_list = []

for i in range(39,86):
    sample_image = cv2.imread(sample_image_path + "{0:03}".format(i) +".png",0)
    sample_image_rgb = cv2.imread(sample_image_rgb_path + "{0:03}".format(i) +".png") 
    length = findDistance(sample_image,sample_image_rgb)
    distance_list.append(round(length))

print(distance_list)
min_ = distance_list[0]
count = 1
cycle_length = []

for i in range(1,len(distance_list)):
    temp = min_ - distance_list[i]
    if temp > 0 and temp < 5:
        count = i
        break
    
print("Cycle Length = {} ".format(count))

[15, 65, 71, 56, 55, 47, 39, 29, 21, 37, 51, 60, 68, 66, 71, 66, 59, 50, 41, 21, 19, 20, 21, 19, 18, 68, 68, 60, 53, 45, 29, 17, 33, 48, 62, 1590, 1589, 67, 75, 67, 57, 46, 36, 30, 19, 19, 18]
Cycle Length = 1 
