In [1]:
import cv2
import numpy as np
import os
import dlib
import pickle
from skimage.measure import compare_ssim as ssim

In [2]:
PATH_SIHOUETTES = "D:\\MINOR_PROJECT\\casia b\\silhouettes"
PATH_VIDEOS = "D:\MINOR_PROJECT\casia b\\videos"

#id = ["{0:03}".format(i) for i in range(1,11)]

id = ["{0:03}".format(i) for i in range(1,5)]

categories = ["nm-01", "nm-02", "nm-03", "nm-04", "nm-05", "nm-06"]

#categories = ["nm-01"]

# For all angles
#angles = ["{0:03}".format(i) for i in range(0,181,18)]

angles = ["{0:03}".format(90)]

image = cv2.imread(PATH_SIHOUETTES + "\\" + id[0] +"\\" + categories[0] + "\\" + angles[0] + "\\" + id[0] +"-" 
                   + categories[0] + "-" + angles[0] + "-" +"003" +".png")


In [77]:
cycle_length = 10
sample_image_rgb = cv2.imread("D:\\MINOR_PROJECT\\casia b\\silhouettes\\001\\nm-01\\090\\001-nm-01-090-047.png")
print(sample_image_rgb)
gei_image = np.zeros(sample_image_rgb.shape,dtype=int)
print(gei_image.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(240, 320, 3)


In [119]:
sample_image_path = "D:\\MINOR_PROJECT\\casia b\\silhouettes\\001\\nm-01\\090\\001-nm-01-090-"
sample_image_rgb_path = "D:\\MINOR_PROJECT\\casia b\\silhouettes\\001\\nm-01\\090\\001-nm-01-090-"
count = 1
sample_image_for_size = cv2.imread("D:\\MINOR_PROJECT\\casia b\\silhouettes\\001\\nm-01\\090\\001-nm-01-090-047.png",0)
gei_image = np.zeros((240,320),dtype = int)
image_list = []
for i in range(47,103):
    if i % 12 != 0:
        sample_image = cv2.imread(sample_image_path + "{0:03}".format(i) +".png",0)
        image_list.append(sample_image)
#         cv2.imshow("gei {}".format(i),gei_image)
#         cv2.waitKey(0)
#         cv2.destroyAllWindows()
    else:
        sample_image = cv2.imread(sample_image_path + "{0:03}".format(i) +".png",0)
        image_list.append(sample_image)
        result = np.zeros(sample_image.shape,dtype=np.int)
        result = np.mean(image_list,axis=0)
#         gei_image = gei_image.astype(np.uint8)
#         ret,gei_imagee = cv2.threshold(gei_image,0,255,0)
        cv2.imshow("gei {}".format(i),result)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        image_list = []
cv2.imshow("gei {}".format(count),gei_image)
cv2.waitKey(0)
cv2.destroyAllWindows()